### ISSUE TITLE
Broken with 1.9

### ISSUE THREAD

**Issue by Phreag** [TheJeterLP/MakeYourOwnCommands#1]
The plugin uses the old org.bukkit.Server.getOnlinePlayers() which was removed in 1.9.
Could you update it?

**Comment by martijn-heil** [comment]
I just opened a [pull request](https://github.com/TheJeterLP/MakeYourOwnCommands/pull/2) with the fix for it, I hope the author will accept it soon.

**Comment by TheJeterLP** [comment]
Thanks for telling me, plugin will be updated soon on bukkitDev.

**Comment by Phreag** [comment]
When will you do this?

**Comment by TheJeterLP** [comment]
Just did it. Bukkit has to approve it now.
